name = Zones
description = Simulates Omega 3.x's zone configuration, with full-width wrappers around groups of regions. Uses Susy for a mobile first responsive layout and grid.
preview = preview.png
template = zones-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[preface]        = Preface
regions[preface2]       = Preface 2
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[postscript]     = Postscript
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/zones/zones.layout.css
